# Generated by Django 6.0.1 on 2026-02-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_composer_is_living'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='sheerpluck_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='imslp_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='score_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
