# Generated by Django 6.0.1 on 2026-02-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_add_trigram_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='title_sort_key',
            field=models.CharField(max_length=500, db_index=True, null=True, blank=True,
                                  help_text="Normalized title for alphabetical sorting"),
        ),
    ]
