# Generated by Django 6.0.1 on 2026-02-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_add_title_sort_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentationcategory',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
