# Generated by Django 6.0.1 on 2026-02-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_increase_instrumentation_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='imslp_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='score_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='sheerpluck_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='work',
            name='title_normalized',
            field=models.CharField(help_text='Lowercase, accents removed for search', max_length=1000),
        ),
        migrations.AlterField(
            model_name='work',
            name='title_sort_key',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized title for alphabetical sorting', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='worksearchindex',
            name='work_instrumentation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='worksearchindex',
            name='work_title',
            field=models.CharField(max_length=1000),
        ),
    ]
