# Generated by Django 6.0.1 on 2026-02-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_increase_field_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentationcategory',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
