# Generated by Django 6.0.1 on 2026-02-10 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_increase_instrumentation_to_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('new_composer', 'New Composer'), ('new_work', 'New Work'), ('edit_composer', 'Edit Composer'), ('edit_work', 'Edit Work'), ('correction', 'Correction'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('merged', 'Merged')], default='pending', max_length=20)),
                ('submitter_name', models.CharField(blank=True, max_length=100)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('suggested_data', models.JSONField(blank=True, help_text='Structured data for the suggestion', null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.composer')),
                ('related_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.work')),
            ],
            options={
                'db_table': 'user_suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_suggestion_status'), models.Index(fields=['created_at'], name='idx_suggestion_created'), models.Index(fields=['suggestion_type'], name='idx_suggestion_type')],
            },
        ),
    ]
